#!/usr/bin/env python3
# Patch the tauri-generated android project with the branded splash screen:
#   - res/values-v31/themes.xml: indigo splash background + pulse-rings icon (API 31+)
#   - res/drawable/splash_icon.xml: the Pulsar mark (rings only, sized for the
#     splash icon's central safe zone — the full-bleed launcher icon looked
#     oversized/cropped as a splash)
#   - MainActivity.onCreate: hold the splash ~700ms (it used to dismiss on the
#     first — still empty — webview frame) + enableEdgeToEdge (an edit that
#     previously lived only in an uncommitted gen/ file, so CI builds lacked it).
#
# gen/android is regenerated by `tauri android init` (CI does this every release
# build), so these changes cannot be committed there — run this script after any
# init, like patch-android-signing.py. Idempotent.
import os, sys

GEN = sys.argv[1] if len(sys.argv) > 1 else "gen/android"
APP = os.path.join(GEN, "app/src/main")
BRAND = "#4E60E8"  # sRGB of the brand indigo oklch(0.555 0.205 272)

# ── 1) drawable/splash_icon.xml — pulse rings, inset to the icon safe zone ──
drawable_dir = os.path.join(APP, "res/drawable")
os.makedirs(drawable_dir, exist_ok=True)
splash_icon = """<?xml version="1.0" encoding="utf-8"?>
<!-- Pulsar mark for the Android 12+ splash: concentric pulse rings only, white on
     the theme's indigo splash background. Sized for the central 2/3 safe zone of
     the 108dp splash icon canvas (the masked launcher icon looked cropped). -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
  <path android:strokeColor="#FFFFFF" android:strokeWidth="2.4" android:strokeAlpha="0.20"
      android:fillColor="#00000000"
      android:pathData="M54,54 m-30,0 a30,30 0 1,1 60,0 a30,30 0 1,1 -60,0"/>
  <path android:strokeColor="#FFFFFF" android:strokeWidth="2.8" android:strokeAlpha="0.45"
      android:fillColor="#00000000"
      android:pathData="M54,54 m-20,0 a20,20 0 1,1 40,0 a20,20 0 1,1 -40,0"/>
  <path android:strokeColor="#FFFFFF" android:strokeWidth="3.2"
      android:fillColor="#00000000"
      android:pathData="M54,54 m-10.6,0 a10.6,10.6 0 1,1 21.2,0 a10.6,10.6 0 1,1 -21.2,0"/>
  <path android:fillColor="#FFFFFF"
      android:pathData="M54,54 m-4.6,0 a4.6,4.6 0 1,1 9.2,0 a4.6,4.6 0 1,1 -9.2,0"/>
</vector>
"""
with open(os.path.join(drawable_dir, "splash_icon.xml"), "w") as f:
    f.write(splash_icon)
print("  + res/drawable/splash_icon.xml")

# ── 2) values-v31/themes.xml — splash attrs (API 31+; below 31 there is no
#      system splash, so no compat needed) ──
v31_dir = os.path.join(APP, "res/values-v31")
os.makedirs(v31_dir, exist_ok=True)
themes_v31 = f"""<resources xmlns:tools="http://schemas.android.com/tools">
    <!-- API 31+ override of the base theme: branded system splash. Keep in sync
         with values/themes.xml (this file REPLACES it on 31+). -->
    <style name="Theme.pulsar_mobile" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        <item name="android:windowSplashScreenBackground">{BRAND}</item>
        <item name="android:windowSplashScreenAnimatedIcon">@drawable/splash_icon</item>
    </style>
</resources>
"""
with open(os.path.join(v31_dir, "themes.xml"), "w") as f:
    f.write(themes_v31)
print("  + res/values-v31/themes.xml")

# ── 3) MainActivity: hold splash ~700ms + edge-to-edge ──
# NOTE: setKeepOnScreenCondition is androidx-core-splashscreen only; the platform
# way (no extra dependency) is to delay the content view's FIRST DRAW — the system
# splash stays up until the first frame is drawn.
ma_path = os.path.join(APP, "java/dev/pulsar/app/MainActivity.kt")
ma = open(ma_path).read()
if "OnPreDrawListener" not in ma:
    ma = """package dev.pulsar.app

import android.os.Bundle
import android.os.SystemClock
import android.view.View
import android.view.ViewTreeObserver
import androidx.activity.enableEdgeToEdge

class MainActivity : TauriActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    enableEdgeToEdge()
    super.onCreate(savedInstanceState)
    // Hold the system splash ~700ms: it dismisses on the first drawn frame, which
    // is the still-empty webview — delaying that first draw keeps the brand splash
    // visible. (Official pre-draw technique; no androidx-splashscreen dependency.)
    val content: View = findViewById(android.R.id.content)
    val t0 = SystemClock.uptimeMillis()
    content.viewTreeObserver.addOnPreDrawListener(object : ViewTreeObserver.OnPreDrawListener {
      override fun onPreDraw(): Boolean {
        return if (SystemClock.uptimeMillis() - t0 >= 700) {
          content.viewTreeObserver.removeOnPreDrawListener(this)
          true
        } else {
          false
        }
      }
    })
  }
}
"""
    open(ma_path, "w").write(ma)
    print("  + MainActivity: splash hold (pre-draw) + edge-to-edge")
else:
    print("  = MainActivity already patched")
print("splash patch done")
